//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoTalentos.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Candidato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidato()
        {
            this.Conhecimento = new HashSet<Conhecimento>();
        }
    
        public int Id { get; set; }

		[Required(ErrorMessage = "*Este campo é obrigatório!")]
		[Display(Name = "Insira seu nome:")]
		public string Nome { get; set; }

		[Required(ErrorMessage = "*Este campo é obrigatório!")]
		[Display(Name = "Insira seu email:")]
		public string Email { get; set; }

		[Required(ErrorMessage = "*Este campo é obrigatório!")]
		[Display(Name = "Insira seu skype (caso não tenha, crie um):")]
		public string Skype { get; set; }

		[Required(ErrorMessage = "*Este campo é obrigatório!")]
		[Display(Name = "Insira seu whatsapp:")]
		public string Whatsapp { get; set; }

		[Display(Name = "Insira seu linkedin:")]
		public string Linkedin { get; set; }

		[Required(ErrorMessage = "*Este campo é obrigatório!")]
		[Display(Name = "Insira sua cidade:")]
		public string Cidade { get; set; }

		[Required(ErrorMessage = "*Este campo é obrigatório!")]
		[Display(Name = "Insira seu estado:")]
		public string Estado { get; set; }

		[Display(Name = "Insira seu portifólio:")]
		public string Portfolio { get; set; }

		[Display(Name = "Menos de quatro horas por dia.")]
		public bool MenosDeQuatro { get; set; }

		[Display(Name = "De quatro a seis horas por dia.")]
		public bool QuatroSeis { get; set; }

		[Display(Name = "De seis a oito horas por dia.")]
		public bool SeisOito { get; set; }

		[Display(Name = "Mais que oito horas por dia (Sério?).")]
		public bool MaisOito { get; set; }

		[Display(Name = "Somente nos fins de semana.")]
		public bool FimSemana { get; set; }

		[Display(Name = "Período da manhã (08:00 ás 12:00).")]
		public bool PManha { get; set; }

		[Display(Name = "Período da tarde (13:00 ás 18:00).")]
		public bool PTarde { get; set; }

		[Display(Name = "Período da noite (19:00 as 22:00).")]
		public bool PNoite { get; set; }

		[Display(Name = "Durante a madrugada (22:00 em diante).")]
		public bool PMadrugada { get; set; }

		[Display(Name = "Horário comercial (das 9:00h às 18:00h).")]
		public bool PComercial { get; set; }

		[Required(ErrorMessage = "*Este campo é obrigatório!")]
		[Display(Name = "Pretensão salarial por hora trabalhada:")]
		public int SalarioHora { get; set; }

		[Display(Name = "Informe seu nome:")]
		public string NomeClienteBanco { get; set; }

		[Display(Name = "Informe seu CPF:")]
		public string CPF { get; set; }

		[Display(Name = "Informe o nome do banco:")]
		public string NomeBanco { get; set; }

		[Display(Name = "Agência:")]
		public string Agencia { get; set; }

		[Display(Name = "Número da conta:")]
		public string NumeroConta { get; set; }

		[Display(Name = "Link CRUD:")]
		public string Link { get; set; }

		[Display(Name = "Conta corrente.")]
		public bool ContaCorrente { get; set; }

		[Display(Name = "Conta poupança.")]
		public bool ContaPoupanca { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conhecimento> Conhecimento { get; set; }
    }
}
